# Generated by Django 5.1.1 on 2024-09-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0002_video_alter_song_audio_file_alter_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_url',
            field=models.CharField(max_length=50, verbose_name='ID Видео'),
        ),
    ]
