# Generated by Django 5.1.1 on 2024-09-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('band', '0006_concert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на мероприятие'),
        ),
    ]
